### ISSUE TITLE
Challenge files

### ISSUE THREAD

**Issue by frustreated** [TrungNguyen1909/ggctf20-teleport#1]
is there any way to get the challenge zip,
or may be the file chall.patch 
thanks for your read. du.

**Comment by TrungNguyen1909** [comment]
You can probably find it at https://g.co/ctf <https://g.co/ctf>
However,
https://storage.googleapis.com/gctf-2020-attachments-project/706c6a5526310585dbb974fd5c681dc11f627f1b2d59b094e8f056b1372045fba54f384f020ab122fba3fbdd83667fd2e5323f344b59734ffc0e66768f1b2357 <https://storage.googleapis.com/gctf-2020-attachments-project/706c6a5526310585dbb974fd5c681dc11f627f1b2d59b094e8f056b1372045fba54f384f020ab122fba3fbdd83667fd2e5323f344b59734ffc0e66768f1b2357>

**Comment by frustreated** [comment]
downloading and learning 
thanks for your quick commit!!
